#!/usr/bin/env ruby

require "bundler/setup"
require "vimr"

require "tty-cursor"
require "io/console"

screen = Vimr::Screen.new

while ch = STDIN.getch
  case ch
  when "q"
    break
  when "j"
    screen.down
  when "k"
    screen.up
  end
end

